[project]
name = "hangman"
version = "0.1.0"
description = "Console-based Hangman game written in Python with input validation, ASCII graphics, and terminal control using ANSI escape sequences."
authors = [
    { name = "Ilia Korepanov", email = "ikorepanov.dev@gmail.com" },
]
dependencies = []
requires-python = ">=3.9.10, <3.12"
readme = "README.md"
license = {text = "MIT"}

[tool.isort]
line_length = 120
force_alphabetical_sort_within_sections = true
include_trailing_comma = true
use_parentheses = true
multi_line_output = 3
force_grid_wrap = 2

[tool.mypy]
follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
ignore_missing_imports = true

# for strict mypy:
disallow_untyped_defs = true

[tool.dev-dependencies]
lint = [
    "isort==5.13.2",
    "flake8==7.1.1",
    "mypy==1.11.2",
    "black==24.10.0",
    "wemake-python-styleguide==0.18.0",
]